from module6hard import Figure, Circle, Triangle, Cube

print()
circle1 = Circle((125, 125, 125), 25)
cube1 = Cube((222, 35, 130), 6, 4, 5)
fig = Figure((255, 255, 255), 11, 23, 43, 21, 33)
triangle = Triangle((233, 232, 231), 33, 66, 55)

# print(circle1)
print(circle1)
print("Закрашен: ", circle1.filled)
print("Радиус:", circle1._Circle__radius)
print("Количество сторон: ", circle1.sides_count)
print("Список сторон: ", circle1.get_sides())
print("Цвет RGB:", circle1.get_color())
print("Меняем цвет на некорректный (455, 13, 14):")
circle1.set_color(455, 13, 14)
print("Цвет RGB:", circle1.get_color())
print("Цвет без изменения")
print("Теперь заменим на корректные значения:")
circle1.set_color(123, 234, 241)
print("Цвет RGB:", circle1.get_color())
print("Цвет изменился")
print(len(circle1))


print("Площадь: ", circle1.get_square())
print()
#
print(cube1)
print("Закрашен: ", cube1.filled)
print("Количество сторон: ", cube1.sides_count)
print("Количество сторон: ", cube1._Figure__sides)
print("Список сторон: ", cube1.get_sides())
print("Цвет RGB:", cube1.get_color())
print("Площадь: ", cube1.get_volume())
print(cube1._Figure__is_valid_sides(12,12,14,15))
print()

print(triangle)
print("Количество сторон: ", triangle.sides_count)
print("Список сторон: ", triangle.get_sides())
print("Цвета: ", triangle.get_color())
print("Закрашена: ", triangle.filled)
print("Площадь: ", triangle.get_square())
print("Периметр: ", len(triangle))
print(triangle._Figure__is_valid_sides(22,33,44))
print()

print(fig)
print("Количество сторон: ", fig.sides_count)
print("Список сторон: ", fig.get_sides())
print("Цвета: ", fig.get_color())
print("Закрашена: ", fig.filled)
print()
